#give the pipeline a name
name: Dart CI

#set conditions to trigger on
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# define what happens when conditions are met
jobs:
  build:
    # use ubuntu's latest OS
    runs-on: ubuntu-latest
    # use the google/dart container (this makes `dart` available to use)
    container:
      image: google/dart:latest

    # checkout the code, run pub get and finally run tests
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze --fatal-infos lib/*.dart test/*.dart

      - name: Run tests
        run: pub run test
